# Default values for tiny-git.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/snippets-n-memes/tiny-git
  pullPolicy: IfNotPresent
  tag: "arm64-20231111.21"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  port: 8080


nodeSelector: {}

tolerations: []

affinity: {}

nginxConfigMap:
  create: false
  namespace: ingress-nginx
pvc:
  StorageClassName: nfs-client
  srvStorage: 100Mi
  keyStorage: 10Mi