apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiny-git.fullname" . }}
  labels:
    {{- include "tiny-git.labels" . | nindent 4 }}
spec:
  type: ClusterIp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    {{- include "tiny-git.selectorLabels" . | nindent 4 }}
